shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.ohmyzsh-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"
use = ["git.plugin.zsh"]

# must be last
[plugins.zsh-fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
