#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=38 \
    color=0xff000000 \
    margin=0 \
    sticky=on \
    padding_left=8 \
    padding_right=8 \
    display=all

sketchybar --default \
    background.drawing=off \
    background.height=28 \
    background.corner_radius=6 \
    icon.color=0xffcdd6f4 \
    icon.font="$FONT_FACE:Medium:18.0" \
    icon.padding_left=6 \
    icon.padding_right=4 \
    label.color=0xffcdd6f4 \
    label.font="$FONT_FACE:Bold:15.0" \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=6

# --- yabai spaces (commented out) ---
# spaces=($'\uf268' $'\uf121' $'\uf120' $'\uf0ac' $'\uf198' $'\uf1bc' $'\uf02d' $'\uf1c0')
# for i in $(seq 1 8); do
#     sketchybar --add space space.$i left \
#         --set space.$i associated_space=$i icon="${spaces[$i]}" ...
# done

# --- aerospace workspaces ---
sketchybar --add event aerospace_workspace_change

declare -A ws_icons
ws_icons=(
    [1-dev]=$'\uf268'
    [2-vscode]=$'\ue70c'
    [3-terminal]=$'\uf120'
    [4-web]=$'\uf0ac'
    [5-slack]=$'\uf198'
    [6-spotify]=$'\uf1bc'
    [7-tbd]=$'\uf128'
    [8-tbd2]=$'\uf129'
)

for ws in 1-dev 2-vscode 3-terminal 4-web 5-slack 6-spotify 7-tbd 8-tbd2; do
    sketchybar --add item aws.$ws left \
        --set aws.$ws \
            icon="${ws_icons[$ws]}" \
            background.color=0xfff5c2e7 \
            background.corner_radius=4 \
            background.height=24 \
            background.drawing=off \
            icon.color=0xffcdd6f4 \
            icon.padding_left=9 \
            icon.padding_right=9 \
            label.drawing=off \
            click_script="aerospace workspace $ws; sketchybar --trigger aerospace_workspace_change" \
            script="$PLUGIN_DIR/aerospace_workspace.sh" \
        --subscribe aws.$ws aerospace_workspace_change mouse.clicked
done

sketchybar --add item front_app left \
    --set front_app \
    background.color=0x00000000 \
    background.border_color=0xffa6da95 \
    background.border_width=2 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:23.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:16.0" \
    label.color=0xffcad3f5 \
    label.padding_left=5

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.color=0x00000000 \
    background.border_color=0xffed8796 \
    padding_left=8 \
    background.border_width=2 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
